apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: {{ .Values.certManager.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: central-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    template:
      type: kuadrant.io/aws
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: aws-credentials
        metadataPolicy: None
