apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-eso-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups:
      - external-secrets.io
    resources:
      - clustersecretstores
      - externalsecrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - operator.openshift.io
    resources:
      - externalsecretsconfigs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-gitops-eso-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-eso-manager
subjects:
  - kind: ServiceAccount
    name: {{ .Values.argocd.serviceAccountName }}
    namespace: {{ .Values.argocd.namespace }}
