apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.namespace }}
      server:
        caProvider:
          type: ConfigMap
          name: {{ .Values.secretStore.caConfigMap }}
          key: {{ .Values.secretStore.caKey }}
          namespace: {{ .Values.namespace }}
      auth:
        serviceAccount:
          name: {{ .Values.serviceAccount.name }}
          namespace: {{ .Values.namespace }}
