gateway:
  namespace: ingress-gateway
  name: prod-gateway
  hostname: "*.demo.leonlevy.lol"
  className: istio

tls:
  issuerName: letsencrypt
  issuerKind: ClusterIssuer
  issuerGroup: cert-manager.io

dns:
  geo: GEO-NA
  weight: 120
  defaultGeo: true
  providerRef: aws-credentials

auth:
  excludePaths:
    - /health

rateLimit:
  limit: 2
  window: 10s

podmonitor:
  meshId: ossm-3
  interval: 30s
