apiVersion: v1
kind: Secret
metadata:
  name: bob-key
  namespace: {{ .Values.keys.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    secret.kuadrant.io/user-id: bob
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: bookinfo
stringData:
  api_key: {{ .Values.keys.bob | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: alice-key
  namespace: {{ .Values.keys.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    secret.kuadrant.io/user-id: alice
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: bookinfo
stringData:
  api_key: {{ .Values.keys.alice | quote }}
type: Opaque
