apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.dns.providerRef }}
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.dns.providerRef }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.dns.providerRef }}
