gateway:
  namespace: ingress-gateway
  name: prod-gateway
  hostname: "*.demo.leonlevy.lol"
  className: istio

tls:
  issuerName: letsencrypt

dns:
  geo: GEO-NA
  weight: 120
  defaultGeo: true

rateLimit:
  limit: 2
  window: 10s
