namespace: secret-store

serviceAccount:
  name: eso-reader

secretStore:
  name: central-secret-store
  caConfigMap: kube-root-ca.crt
  caKey: ca.crt

argocd:
  namespace: openshift-gitops
  serviceAccountName: openshift-gitops-argocd-application-controller
