app:
  namespace: bookinfo

gateway:
  name: prod-gateway
  namespace: ingress-gateway

hostname: bookinfo.demo.leonlevy.lol

images:
  details: docker.io/istio/examples-bookinfo-details-v1:1.20.3
  productpage: docker.io/istio/examples-bookinfo-productpage-v1:1.20.3
  ratings: quay.io/llevy/ratings:cluster
  reviewsV1: docker.io/istio/examples-bookinfo-reviews-v1:1.20.3
  reviewsV2: docker.io/istio/examples-bookinfo-reviews-v2:1.20.3
  reviewsV3: docker.io/istio/examples-bookinfo-reviews-v3:1.20.3

ratings:
  clusterName: CLUSTER-EAST

podmonitor:
  meshId: ossm-3
  interval: 30s

rateLimit:
  bob:
    limit: 20
    window: 10s
  general:
    limit: 2
    window: 10s

keys:
  namespace: kuadrant-system
  bob: IAMBOB
  alice: IAMALICE
